In [10]:
import numpy as np
# 1D array
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [11]:
import numpy as np
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
import numpy as np
ones_array = np.ones((3, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
import numpy as np
range_array = np.arange(0, 10, 2)
print(range_array)

[0 2 4 6 8]


In [14]:
import numpy as np
linear_array = np.linspace(0, 1, 5)
print(linear_array)

[0.   0.25 0.5  0.75 1.  ]


In [15]:
#2D Array
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])
print(b)

(2, 3)
1 2 4
[[1 2 3]
 [4 5 6]]


In [16]:
import numpy as np
random_array = np.random.rand(2, 3)
print(random_array)

[[0.23343487 0.02947623 0.59416855]
 [0.58418766 0.95801548 0.36188929]]


In [17]:
arr1 = np.array([[4, 7], [2, 6]], dtype=np.float64)
arr2 = np.array([[3, 6], [2, 8]], dtype=np.float64)
print(arr1)
print(arr2)
print(np.add(arr1, arr2))
print(np.sum(arr1))
print(np.sqrt(arr1))
print(arr1.T)

[[4. 7.]
 [2. 6.]]
[[3. 6.]
 [2. 8.]]
[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [18]:
import numpy as np
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))
print()
print(x - y)
print(np.subtract(x, y))
print()
print(x * y)
print(np.multiply(x, y))
print()
print(x / y)
print(np.divide(x, y))
print()
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [19]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x)
print(y)
v = np.array([9,10])
w = np.array([11, 12])
print(v)
print(w)
# Inner product of vectors; both produce 219 (9×11)+(10×12)
print(v.dot(w))
print(np.dot(v, w))
print(np.multiply(v,w))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 9 10]
[11 12]
219
219
[ 99 120]


In [20]:
print(x.dot(v))
print(np.dot(x, v)) #(1×9)+(2×10)=9+20=29 (3×9)+(4×10)=27+40=67

[29 67]
[29 67]


In [21]:
import numpy as np
array = np.array([1, 2, 3])
mean_value = np.mean(array)
print(mean_value)

2.0


In [22]:
import numpy as np
array = np.array([1, 2, 3])
print(array)
max_val = np.max(array)
min_val = np.min(array)
print(max_val)
print(min_val)

[1 2 3]
3
1


In [23]:
import numpy as np
array = np.array([1, 2, 3, 4])
element = array[2]
print(element)

3


In [24]:
import numpy as np
subset = array[1:3]
print(subset)

[2 3]


In [25]:
import numpy as np
sorted_array = np.sort(np.array([3, 1, 2]))
print(sorted_array)

[1 2 3]


In [26]:
#np.where(): Returns the indices of elements that satisfy a condition.
import numpy as np
array = np.array([1, 2])
indices = np.where(array > 2)
print(indices)

(array([], dtype=int64),)
